theme: jekyll-theme-cayman

# Site settings
title:
  en: PlagEvalRus
  ru: PlagEvalRus
email: plagevalrus@gmail.com
participants_group:  https://groups.google.com/forum/#!forum/plagevalrus2017
description:
  en: text
  ru: текст
index:
  en: enindex.html
  ru: index.html
